gui:
  scrollHeight: 3
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  language: en
  timeFormat: 02 Jan 06
  shortTimeFormat: 15:04
  theme:
    activeBorderColor:
      - default
      - bold
    inactiveBorderColor:
      - gray
    searchingActiveBorderColor:
      - yellow
    optionsTextColor:
      - '#ccc'
    selectedLineBgColor:
      - gray
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
  showListFooter: false
  showFileTree: false
  showRandomTip: false
  statusPanelView: allBranchesLog
git:
  autoFetch: false
  autoRefresh: false
  branchLogCmd: git ls --color=always {{branchName}} --
  allBranchesLogCmd: git lsa --color=always
  parseEmoji: true
  truncateCopiedCommitHashesTo: 8
disableStartupPopups: true
promptToReturnFromSubprocess: false
