[templates]
track = "Tracks/{item.artist} - {item.title_version}"
album = "Albums/{album.artist} - {album.title}/{item.number:02d}. {item.artist} - {item.title_version}"

[download]
track_quality = "max"
download_path = "/run/media/greg/data/music"
update_mtime = true
atmos_filter = "allow"

[metadata]
cover = true
