"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [2, 3, 4]
show_hidden = true
show_symlink = false
scrolloff = 3

[preview]
max_width = 1920
max_height = 1080

[opener]
edit = [{ run = '$EDITOR "$@"', block = true, desc = "Edit" }]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$0")"', desc = "Reveal", for = "linux" },
  { run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
]
extract = [
  { run = 'unar "$1"', desc = "Extract", for = "unix" },
  { run = 'unar "%1"', desc = "Extract", for = "windows" },
]
play = [
  { run = 'mpv "$@"', orphan = true, desc = "Play", for = "unix" },
  { run = 'mpv "%1"', orphan = true, desc = "Play", for = "windows" },
]

[open]
rules = [
  { name = "*/", use = ["edit", "open", "reveal"] },
  { mime = "text/*", use = ["edit", "reveal"] },
  { mime = "*/{csv,javascript,json}", use = ["edit", "reveal"] },
  { mime = "inode/x-empty", use = ["edit", "reveal"] },
  { mime = "image/*", use = ["open", "reveal"] },
  { mime = "{audio,video}/*", use = ["play", "reveal"] },
  { mime = "application/*zip", use = ["extract", "reveal"] },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = ["extract", "reveal"] },
  { mime = "*", use = ["open", "reveal"] },
]

[plugin]
previewers = [
  { name = "*/", run = "folder", sync = true },
  { mime = "text/*", run = "code" },
  { mime = "*/{csv,javascript,json}", run = "code" },
  { mime = "image/*", run = "image" },
  { mime = "video/*", run = "video" },
  { mime = "application/*zip", run = "archive" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", run = "archive" },
  { mime = "application/pdf", run = "pdf" },
  { name = "*", run = "file" },
]

[input]
# cd
cd_title = "Change directory:"
cd_origin = "top-center"
cd_offset = [0, 2, 50, 3]

# create
create_title = "Create:"
create_origin = "top-center"
create_offset = [0, 2, 50, 3]

# rename
rename_title = "Rename:"
rename_origin = "hovered"
rename_offset = [0, 1, 50, 3]

# trash
trash_title = "Move {n} selected file{s} to trash? (y/N)"
trash_origin = "top-center"
trash_offset = [0, 2, 50, 3]

# delete
delete_title = "Delete {n} selected file{s} permanently? (y/N)"
delete_origin = "top-center"
delete_offset = [0, 2, 50, 3]

# filter
filter_title = "Filter:"
filter_origin = "top-center"
filter_offset = [0, 2, 50, 3]

# find
find_title = ["Find next:", "Find previous:"]
find_origin = "top-center"
find_offset = [0, 2, 50, 3]

# search
search_title = "Search via {n}:"
search_origin = "top-center"
search_offset = [0, 2, 50, 3]

# shell
shell_title = ["Shell:", "Shell (block):"]
shell_origin = "top-center"
shell_offset = [0, 2, 50, 3]

# overwrite
overwrite_title = "Overwrite an existing file? (y/N)"
overwrite_origin = "top-center"
overwrite_offset = [0, 2, 50, 3]

# quit
quit_title = "{n} task{s} running, sure to quit? (y/N)"
quit_origin = "top-center"
quit_offset = [0, 2, 50, 3]

[select]
open_title = "Open with:"
open_origin = "hovered"
open_offset = [0, 1, 50, 7]

[which]
sort_by = "none"
sort_sensitive = false
sort_reverse = false

[log]
enabled = false

[headsup]
