[[columns]]
kind = "Pid"
style = "Blue"
numeric_search = true
nonnumeric_search = false
align = "Right"
header = "pid"

[[columns]]
kind = "User"
style = "Cyan"
numeric_search = false
nonnumeric_search = true
align = "Left"
max_width = 4
header = "usr"

[[columns]]
kind = "UsageCpu"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Right"
header = "cpu"

[[columns]]
kind = "UsageMem"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Right"
header = "mem"

[[columns]]
kind = "VmHwm"
style = "ByUnit"
numeric_search = false
nonnumeric_search = false
align = "Right"
header = "mem"

[[columns]]
kind = "MultiSlot"
style = "ByUnit"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "Command"
style = "BrightWhite"
numeric_search = false
nonnumeric_search = true
align = "Left"
header = "cmd"

[style]
header = "White"
unit = "BrightBlack"

  [style.by_percentage]
  color_000 = "White"
  color_025 = "Yellow"
  color_050 = "Yellow"
  color_075 = "Red"
  color_100 = "Red"

  [style.by_unit]
  color_k = "White"
  color_m = "Yellow"
  color_g = "Red"
  color_t = "Red"
  color_p = "Red"
  color_x = "White"

[sort]
column = 2
order = "Descending"
