[settings]

idiomatic_version_file_enable_tools = ["bun", "node"]

[tools]

bun = "latest"

node = "latest"

"npm:npm" = "latest"
"npm:eslint" = { version = "latest", depends = ["npm:npm"] }
"npm:neovim" = { version = "latest", depends = ["npm:npm"] }
"npm:typescript" = { version = "latest", depends = ["npm:npm"] }
