"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
use = ""

[manager]

cwd = { fg = "cyan" }

hovered = { reversed = true }
preview_hovered = { bold = true }

find_keyword = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "lightgreen", bg = "lightgreen" }
marker_cut = { fg = "lightred", bg = "lightred" }
marker_marked = { fg = "lightcyan", bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "white", bg = "green" }
count_cut = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "yellow" }

border_symbol = " "
border_style = { fg = "black" }


[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "gray", bg = "gray" }

# Mode
mode_normal = { bg = "blue", bold = true }
mode_select = { bg = "red", bold = true }
mode_unset = { bg = "red", bold = true }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "darkgray" }


[select]
border = { fg = "darkgray" }
active = { fg = "magenta", bold = true }
inactive = {}


[input]
border = { fg = "darkgray" }
title = { fg = "magenta" }
value = {}
selected = { reversed = true }


# : Completion {{{

[completion]
border = { fg = "blue" }
active = { reversed = true }
inactive = {}

# Icons
icon_file = ""
icon_folder = ""
icon_command = ""




[tasks]
border = { fg = "blue" }
title = {}
hovered = { fg = "magenta", underline = true }


[which]
cols = 2
mask = { bg = "reset" }
cand = { fg = "cyan" }
rest = { fg = "darkgray" }
desc = { fg = "magenta" }
separator = " "


[help]
on = { fg = "cyan" }
run = { fg = "magenta" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "black", bg = "white" }


[notify]
title_info = { fg = "green" }
title_warn = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info = ""
icon_warn = ""
icon_error = ""

[filetype]

rules = [
  { name = "*.{cow,fsa,mrimg,wim}", fg = "magenta" },

  { name = "*.iso", fg = "magenta" },

  { name = "*.git/", fg = "gray" },

  { name = "*.dockerignore", fg = "gray" },
  { name = "*.editorconfig", fg = "gray" },
  { name = "*.env", fg = "gray" },
  { name = "*.eslintrc", fg = "gray" },
  { name = "*.git", fg = "gray" },
  { name = "*.gitattributes", fg = "gray" },
  { name = "*.gitignore", fg = "gray" },
  { name = "*.gitmodules", fg = "gray" },
  { name = "*.luacheckrc", fg = "gray" },
  { name = "*.pylintrc", fg = "gray" },

  # npmrc .luarc.json .stylua.toml .taplo.toml

  { name = "*.{backup,bak,log,off,old,orig,original,part,swp,tmp}", fg = "darkgray" },

  { mime = "image/*", fg = "magenta" },

  { mime = "{audio,video}/*", fg = "magenta" },

  { mime = "application/*zip", fg = "yellow" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "yellow" },

  { name = "*", is = "link", fg = "blue" },
  { name = "*/", is = "link", fg = "blue" },
  { name = "*", is = "orphan", fg = "red" },
  { name = "*/", is = "orphan", fg = "red" },

  { name = "*", is = "exec", fg = "green" },

  { name = "*", fg = "reset" },
  { name = "*/", fg = "cyan" },
]

[icon]

rules = [
  { name = "*.{cow,fsa,mrimg,wim}", text = "󰋊" },

  { name = "*.iso", text = "󰗮" },

  { name = "*.dockerignore", text = "" },
  { name = "*.editorconfig", text = "" },
  { name = "*.env", text = "" },
  { name = "*.eslintrc", text = "" },
  { name = "*.git", text = "" },
  { name = "*.gitattributes", text = "" },
  { name = "*.gitignore", text = "" },
  { name = "*.gitmodules", text = "" },
  { name = "*.luacheckrc", text = "" },
  { name = "*.pylintrc", text = "" },

  { name = "*.{backup,bak,log,off,old,orig,original,part,swp,tmp}", text = "󰘓" },

  { name = "*.{jpeg,jpg,png,svg}", text = "" },

  { name = "*.{mp3,ogg,opus}", text = "" },
  { name = "*.{mkv,mp4,webm}", text = "" },

  { name = "*.{7z,gz,rar,tar,zip}", text = "" },

  { name = "*", is = "link", text = "󰌷" },
  { name = "*/", is = "link", text = "󰌷" },
  { name = "*", is = "orphan", text = "󰌸" },
  { name = "*/", is = "orphan", text = "󰌸" },

  { name = "*.c", text = "" },
  { name = "*.cpp", text = "" },
  { name = "*.cs", text = "󰌛" },
  { name = "*.css", text = "" },
  { name = "*.go", text = "" },
  { name = "*.h", text = "" },
  { name = "*.hpp", text = "" },
  { name = "*.html", text = "" },
  { name = "*.js", text = "" },
  { name = "*.jsx", text = "" },
  { name = "*.lua", text = "" },
  { name = "*.nix", text = "" },
  { name = "*.nu", text = ">" },
  { name = "*.py", text = "" },
  { name = "*.rb", text = "" },
  { name = "*.rs", text = "" },
  { name = "*.scss", text = "" },
  { name = "*.sh", text = "" },
  { name = "*.zsh", text = "" },
  { name = "*.ts", text = "" },
  { name = "*.vim", text = "" },

  { name = "*.ps1", text = "" },
  { name = "*.cmd", text = "" },
  { name = "*.bat", text = "" },
  { name = "*.exe", text = "" },

  { name = "Dockerfile", text = "󰡨" }, # not working

  { name = "*.conf", text = "" },
  { name = "config", text = "" }, # not working
  { name = "*.rules", text = "" },
  { name = "*.service", text = "" },
  { name = "*.timer", text = "󰅐" },
  { name = "*.ini", text = "" },
  { name = "*.json", text = "" },
  { name = "*.jsonc", text = "" },
  { name = "*.kdl", text = "" },
  { name = "*.md", text = ""  },
  { name = "*.toml", text = "" },
  { name = "*.txt", text = "" },
  { name = "*.yaml", text = "" },
  { name = "*.yml", text = "" },
  { name = "*.xml", text = "󰗀" },
  { name = "*.tmTheme", text = "󰗀" },

  { name = "*.[ot]tf", text = "" },
  { name = "*.icm", text = "󰏘" },

  { name = "*.exe", text = "" },

  { name = ".zprofile", text = "" }, # they are not working
  { name = ".zshenv", text = "" },
  { name = ".zshrc", text = "" },
  # dir_colors


  { name = "*.git/", text = "" },

  { name = "*.csv", text = "" },
  { name = "*.docx", text = "" },
  { name = "*.pdf", text = "" },
  { name = "*.xlsx", text = "" },
  { name = "*.epub", text = "" },

  { name = "*", text = "" },
  { name = "*/", text = "" },
]
