[env]
DOTNET_CLI_HOME = "{{env.XDG_CACHE_HOME}}/dotnet"

[tools]

  [tools."dotnet:csharp-ls"]
  version = "latest"

    [tools."dotnet:csharp-ls".install_env]
    DOTNET_CLI_TELEMETRY_OPTOUT = "1"
    DOTNET_GENERATE_ASPNET_CERTIFICATE = "0"
    DOTNET_NOLOGO = "1"
