config_version = 2

[dock]
enabled = true
launcher_position = "start"
pinned = ["kitty", "brave-origin"]
reserve_space = false
smart_auto_hide = true

[shell.screen_corners]
size = 16

[shell.shadow]
alpha = 0.5

[theme]
builtin = "Gruvbox"
community_palette = "Gruvbox Material"
source = "community"

[wallpaper]
directory = "~/code/walls"
directory_dark = "~/code/walls"
directory_light = "~/code/walls"
transition = ["fade"]
transition_duration = 1000

  [wallpaper.automation]
  enabled = true
  interval_seconds = 3600
  recursive = false

  [wallpaper.default]
  path = "/home/greg/code/walls/women.jpg"
