# env

XDG_CACHE_HOME=$HOME/.cache
XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state

# path

PATH=$HOME/.local/bin:$XDG_DATA_HOME/mise/shims:$XDG_DATA_HOME/cargo/bin:$PATH

  # $XDG_DATA_HOME/bun/bin
  # $XDG_DATA_HOME/go/bin
  # $XDG_DATA_HOME/npm/bin

# zsh

ZDOTDIR=$XDG_CONFIG_HOME/zsh

# copilot (vscode)

COPILOT_HOME=$XDG_CONFIG_HOME/copilot

# docker (intellij & vscode)

DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

# gnupg

GNUPGHOME=$XDG_DATA_HOME/gnupg

# go (vscode)

GOCACHE=$XDG_CACHE_HOME/go
GOPATH=$XDG_DATA_HOME/go

# node (vscode)

NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

# vscode

VSCODE_CLI_DATA_DIR=$XDG_CONFIG_HOME/vscode/cli
VSCODE_PORTABLE=$XDG_CONFIG_HOME/vscode
