import = ["~/.config/alacritty/gruvbox-material-dark.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.95

[window.dimensions]
columns = 160
lines = 40

[window.padding]
x = 5
y = 5

[font]
builtin_box_drawing = false
size = 12

[font.bold]
family = "Cascadia Code"
style = "Semibold"

[font.bold_italic]
family = "Cascadia Code"
style = "Semibold Italic"

[font.italic]
family = "Cascadia Code"
style = "Italic"

[font.normal]
family = "Cascadia Code"
style = "Regular"

[colors]
transparent_background_colors = true

[cursor]
unfocused_hollow = false

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
