[colors.primary]
background = "#32302f"
foreground = "#d4be98"

[colors.cursor]
cursor = "#928374"
text = "#32302f"

[colors.vi_mode_cursor]
cursor = "#928374"
text = "#32302f"

[colors.search.matches]
background = "#b47109"
foreground = "#32302f"

[colors.search.focused_match]
background = "#b47109"
foreground = "#32302f"

[colors.line_indicator]
background = "#32302f"
foreground = "#665c54"

[colors.footer_bar]
background = "#32302f"
foreground = "#665c54"

[colors.selection]
background = "#d4be98"
foreground = "#32302f"

[colors.normal]
black = "#3c3836"
blue = "#45707a"
cyan = "#4c7a5d"
green = "#6c782e"
magenta = "#945e80"
red = "#c14a4a"
white = "#928374"
yellow = "#b47109"

[colors.bright]
black = "#665c54"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#d4be98"
yellow = "#d8a657"
