[colors.primary]
background = "#32302f" # bg0
foreground = "#d4be98" # fg0

[colors.cursor]
cursor = "#928374" # grey1
text = "#32302f" # bg0

[colors.vi_mode_cursor]
cursor = "#928374" # grey1
text = "#32302f" # bg0

[colors.selection]
background = "#504945" # bg3
foreground = "CellForeground"

[colors.normal]
black = "#3c3836" # bg1
red = "#c14a4a" # term_red
green = "#6c782e" # term_green
yellow = "#b47109" # term_yellow
blue = "#45707a" # term_blue
magenta = "#945e80" # term_magenta
cyan = "#4c7a5d" # term_cyan
white = "#928374" # grey1

[colors.bright]
black = "#665c54" # bg5
red = "#ea6962" # red
green = "#a9b665" # green
yellow = "#d8a657" # yellow
blue = "#7daea3" # blue
magenta = "#d3869b" # magenta
cyan = "#89b482" # cyan
white = "#d4be98" # fg0

[colors.hints.start]
background = "#45707a" # term_blue
foreground = "#d4be98" # fg0

[colors.hints.end]
background = "#45707a" # term_blue
foreground = "#d4be98" # fg0

[colors.line_indicator]
background = "#928374" # grey1
foreground = "#32302f" # bg0

[colors.footer_bar]
background = "#32302f" # bg0
foreground = "#928374" # grey1

[colors.search.matches]
background = "#d8a657" # yellow
foreground = "#32302f" # bg0

[colors.search.focused_match]
background = "#b47109" # term_yellow
foreground = "#32302f" # bg0

